services:
  watchtower:
    image: containrrr/watchtower
    command:
      - --label-enable
      - --interval=30
      - --rolling-restart
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/.docker/config.json:/config.json
    restart: unless-stopped

  redis:
    image: redis:latest
    volumes:
      - redis-data-prod:/data
    restart: unless-stopped

  backend:
    image: ghcr.io/lechaosx/cv-generator/backend:prod
    environment:
      OPENAI_KEY: /run/secrets/openai_key
    secrets:
      - openai_key
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  caddy:
    image: caddy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy-data:/data
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis-data-prod:
  caddy-data:

secrets:
  openai_key:
    file: ./secrets/openai_key
