services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - postgres_password
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: 
      context: backend
      target: dev
    environment:
      POSTGRES_HOST: db
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - ./backend/alembic:/app/alembic
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/src:/app/src
      - ./backend/data:/app/data
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: 
      context: frontend
      target: dev
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
    depends_on:
      - backend

  nginx:
    build: 
      context: nginx
      target: dev
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:

secrets:
  postgres_password:
    file: ./secrets/postgres_password