services:
  backend:
    build:
      context: .
      target: dev
    environment:
      DOMAINS_CONFIG: ${DOMAINS_CONFIG:-/config/domains.json}
      DEFAULT_CV: /data/default.yaml
    volumes:
      - ./server:/app/server
      - ./config/domains.json:/config/domains.json:ro
      - ${DEFAULT_CV:-./data/cv.yaml}:/data/default.yaml:ro
      - diskcache:/data

  ts-builder:
    image: oven/bun:alpine
    working_dir: /app
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "bun install && bun run serve"

  caddy:
    image: caddy:alpine
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - ts-builder

volumes:
  diskcache:
