services:
  backend:
    build: 
      context: backend
      target: prod
    environment:
      OPENAI_KEY: /run/secrets/openai_key
    secrets:
      - openai_key
    depends_on:
      - redis

  frontend:
    build: 
      context: frontend
      target: prod
    depends_on:
      - backend

  nginx:
    build: 
      context: nginx
      target: prod
    ports:
      - "443:443"
    secrets:
      - source: nginx_key
        target: /etc/nginx/ssl/nginx.key
      - source: nginx_cert
        target: /etc/nginx/ssl/nginx.crt
    depends_on:
      - frontend
      - backend
  
  redis:
    image: redis:latest
    volumes:
      - redis-data-prod:/data

volumes:
  redis-data-prod:

secrets:
  openai_key:
    file: ./secrets/openai_key
  nginx_cert:
    file: ./secrets/nginx.crt
  nginx_key:
    file: ./secrets/nginx.key