services:
  backend:
    build: 
      context: backend
      target: dev
    environment:
      OPENAI_KEY: /run/secrets/openai_key
    secrets:
      - openai_key
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data
    depends_on:
      - redis

  frontend:
    build: 
      context: frontend
      target: dev
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
    depends_on:
      - backend

  nginx:
    build: 
      context: nginx
      target: dev
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  redis-data:

secrets:
  openai_key:
    file: ./secrets/openai_key
