name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Docker registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        target: prod
        platforms: linux/arm64
        push: true
        tags: ghcr.io/xdlaba02/cv-generator/backend:prod

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        target: prod
        platforms: linux/arm64
        push: true
        tags: ghcr.io/xdlaba02/cv-generator/frontend:prod